include                     color.conf

#font_family                Fira Code
#font_family                FiraCode Nerd Font Mono
#font_family                VictorMono Nerd Font Mono
#font_family                VictorMono Nerd Font
#font_family                TerminessTTF Nerd Font
#font_family                JetBrainsMono Nerd Font Mono
font_family                 Cascadia Code Light

bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   13.0

disable_ligatures           cursor

remember_window_size        no
initial_window_width        120c
initial_window_height       48c


copy_on_select              clipboard
map cmd+shift+v             paste_from_buffer a1
map cmd+shift+c             paste_to_buffer a1

sync_to_monitor             yes

map ctrl+shift+plus         change_font_size all +2.0
map ctrl+shift+minus        change_font_size_all -2.0
map ctrl+shift+backspace    change_font_size all 0

#shell

close_on_child_death        yes
