[general]
destination = "$HOME/.config/hypr/monitors.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_ADP0"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_ADP0"


[profiles.docked]
config_file = "/home/dabrown/.config/hyprdynamicmonitors/hyprconfigs/docked.go.tmpl"
config_file_type = "template"
[profiles.docked.conditions]

[[profiles.docked.conditions.required_monitors]]
description = "BOE NE160WUM-NX2"
monitor_tag = "laptop"

[[profiles.docked.conditions.required_monitors]]
description = "ASUSTek COMPUTER INC MS27UC S9LMMU000204"
monitor_tag = "external"


[profiles.laptop]
config_file = "/home/dabrown/.config/hyprdynamicmonitors/hyprconfigs/laptop.go.tmpl"
config_file_type = "template"
[profiles.laptop.conditions]

[[profiles.laptop.conditions.required_monitors]]
description = "BOE NE160WUM-NX2"
monitor_tag = "laptop"
